/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ExecutionManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "executionIds"
      | "executions"
      | "getExecutionCount"
      | "triggerExecution"
      | "updateExecutionState"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ExecutionStateChanged" | "ExecutionTriggered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "executionIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getExecutionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "triggerExecution",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateExecutionState",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "executionIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "executions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getExecutionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "triggerExecution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateExecutionState",
    data: BytesLike
  ): Result;
}

export namespace ExecutionStateChangedEvent {
  export type InputTuple = [strategyId: BytesLike, state: BigNumberish];
  export type OutputTuple = [strategyId: string, state: bigint];
  export interface OutputObject {
    strategyId: string;
    state: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutionTriggeredEvent {
  export type InputTuple = [
    strategyId: BytesLike,
    executor: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    strategyId: string,
    executor: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    strategyId: string;
    executor: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ExecutionManager extends BaseContract {
  connect(runner?: ContractRunner | null): ExecutionManager;
  waitForDeployment(): Promise<this>;

  interface: ExecutionManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  executionIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  executions: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint] & {
        strategyId: string;
        executor: string;
        timestamp: bigint;
        state: bigint;
      }
    ],
    "view"
  >;

  getExecutionCount: TypedContractMethod<[], [bigint], "view">;

  triggerExecution: TypedContractMethod<
    [_strategyId: BytesLike],
    [void],
    "nonpayable"
  >;

  updateExecutionState: TypedContractMethod<
    [_strategyId: BytesLike, _state: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "executionIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "executions"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint] & {
        strategyId: string;
        executor: string;
        timestamp: bigint;
        state: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getExecutionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "triggerExecution"
  ): TypedContractMethod<[_strategyId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateExecutionState"
  ): TypedContractMethod<
    [_strategyId: BytesLike, _state: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ExecutionStateChanged"
  ): TypedContractEvent<
    ExecutionStateChangedEvent.InputTuple,
    ExecutionStateChangedEvent.OutputTuple,
    ExecutionStateChangedEvent.OutputObject
  >;
  getEvent(
    key: "ExecutionTriggered"
  ): TypedContractEvent<
    ExecutionTriggeredEvent.InputTuple,
    ExecutionTriggeredEvent.OutputTuple,
    ExecutionTriggeredEvent.OutputObject
  >;

  filters: {
    "ExecutionStateChanged(bytes32,uint8)": TypedContractEvent<
      ExecutionStateChangedEvent.InputTuple,
      ExecutionStateChangedEvent.OutputTuple,
      ExecutionStateChangedEvent.OutputObject
    >;
    ExecutionStateChanged: TypedContractEvent<
      ExecutionStateChangedEvent.InputTuple,
      ExecutionStateChangedEvent.OutputTuple,
      ExecutionStateChangedEvent.OutputObject
    >;

    "ExecutionTriggered(bytes32,address,uint256)": TypedContractEvent<
      ExecutionTriggeredEvent.InputTuple,
      ExecutionTriggeredEvent.OutputTuple,
      ExecutionTriggeredEvent.OutputObject
    >;
    ExecutionTriggered: TypedContractEvent<
      ExecutionTriggeredEvent.InputTuple,
      ExecutionTriggeredEvent.OutputTuple,
      ExecutionTriggeredEvent.OutputObject
    >;
  };
}
