/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface StrategyRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getStrategyCount"
      | "registerStrategy"
      | "strategies"
      | "strategyIds"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "StrategyRegistered"): EventFragment;

  encodeFunctionData(
    functionFragment: "getStrategyCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerStrategy",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "strategies",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "strategyIds",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getStrategyCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "strategies", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "strategyIds",
    data: BytesLike
  ): Result;
}

export namespace StrategyRegisteredEvent {
  export type InputTuple = [
    id: BytesLike,
    user: AddressLike,
    timestamp: BigNumberish,
    healthScore: BigNumberish,
    reportHash: BytesLike
  ];
  export type OutputTuple = [
    id: string,
    user: string,
    timestamp: bigint,
    healthScore: bigint,
    reportHash: string
  ];
  export interface OutputObject {
    id: string;
    user: string;
    timestamp: bigint;
    healthScore: bigint;
    reportHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StrategyRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): StrategyRegistry;
  waitForDeployment(): Promise<this>;

  interface: StrategyRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getStrategyCount: TypedContractMethod<[], [bigint], "view">;

  registerStrategy: TypedContractMethod<
    [_id: BytesLike, _healthScore: BigNumberish, _reportHash: BytesLike],
    [void],
    "nonpayable"
  >;

  strategies: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, string] & {
        id: string;
        user: string;
        timestamp: bigint;
        healthScore: bigint;
        reportHash: string;
      }
    ],
    "view"
  >;

  strategyIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getStrategyCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerStrategy"
  ): TypedContractMethod<
    [_id: BytesLike, _healthScore: BigNumberish, _reportHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "strategies"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, bigint, bigint, string] & {
        id: string;
        user: string;
        timestamp: bigint;
        healthScore: bigint;
        reportHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "strategyIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getEvent(
    key: "StrategyRegistered"
  ): TypedContractEvent<
    StrategyRegisteredEvent.InputTuple,
    StrategyRegisteredEvent.OutputTuple,
    StrategyRegisteredEvent.OutputObject
  >;

  filters: {
    "StrategyRegistered(bytes32,address,uint256,uint8,bytes32)": TypedContractEvent<
      StrategyRegisteredEvent.InputTuple,
      StrategyRegisteredEvent.OutputTuple,
      StrategyRegisteredEvent.OutputObject
    >;
    StrategyRegistered: TypedContractEvent<
      StrategyRegisteredEvent.InputTuple,
      StrategyRegisteredEvent.OutputTuple,
      StrategyRegisteredEvent.OutputObject
    >;
  };
}
