/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
    '../../packages/ui/src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#051424',
        foreground: '#d4e4fa',
        surface: '#051424',
        'surface-dim': '#051424',
        'surface-bright': '#2c3a4c',
        'surface-variant': '#273647',
        'surface-container-lowest': '#010f1f',
        'surface-container-low': '#0d1c2d',
        'surface-container': '#122131',
        'surface-container-high': '#1c2b3c',
        'surface-container-highest': '#273647',
        'surface-tint': '#adc6ff',
        'on-surface': '#d4e4fa',
        'on-surface-variant': '#c1c6d7',
        'on-background': '#d4e4fa',
        'inverse-surface': '#d4e4fa',
        'inverse-on-surface': '#233143',
        'inverse-primary': '#005bc1',
        primary: {
          DEFAULT: '#adc6ff',
          foreground: '#002e69',
        },
        'on-primary': '#002e69',
        'primary-container': '#4b8eff',
        'on-primary-container': '#00285c',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#adc6ff',
        'on-primary-fixed': '#001a41',
        'on-primary-fixed-variant': '#004493',
        secondary: '#ddb7ff',
        'on-secondary': '#490080',
        'secondary-container': '#6f00be',
        'on-secondary-container': '#d6a9ff',
        'secondary-fixed': '#f0dbff',
        'secondary-fixed-dim': '#ddb7ff',
        'on-secondary-fixed': '#2c0051',
        'on-secondary-fixed-variant': '#6900b3',
        tertiary: '#4edea3',
        'on-tertiary': '#003824',
        'tertiary-container': '#00a572',
        'on-tertiary-container': '#00311f',
        'tertiary-fixed': '#6ffbbe',
        'tertiary-fixed-dim': '#4edea3',
        'on-tertiary-fixed': '#002113',
        'on-tertiary-fixed-variant': '#005236',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        outline: '#8b90a0',
        'outline-variant': '#414755',
        card: {
          DEFAULT: '#122131',
          foreground: '#d4e4fa',
        },
        muted: {
          DEFAULT: '#1c2b3c',
          foreground: '#c1c6d7',
        },
        accent: {
          DEFAULT: '#4edea3',
          foreground: '#003824',
        },
        border: 'rgba(255, 255, 255, 0.08)',
        flare: {
          orange: '#FF4A00',
          dark: '#0D0E12',
          card: '#16181F',
        },
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
        md: '0.375rem',
        sm: '0.125rem',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        unit: '8px',
        md: '16px',
        lg: '24px',
        gutter: '24px',
        xl: '48px',
        'container-max': '1440px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'Inter', 'sans-serif'],
        display: ['Syne', 'Outfit', '"Plus Jakarta Sans"', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
        'body-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'display-lg-mobile': ['Syne', 'Outfit', 'sans-serif'],
        'display-lg': ['Syne', 'Outfit', 'sans-serif'],
        'title-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'mono-data': ['"JetBrains Mono"', 'monospace'],
        'label-caps': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-md': ['Syne', 'Outfit', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'display-lg-mobile': [
          '32px',
          { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' },
        ],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'title-sm': ['18px', { lineHeight: '24px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'mono-data': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'headline-md': [
          '24px',
          { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
      },
      scale: {
        98: '0.98',
      },
    },
  },
  plugins: [],
};
