/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IFlareContractRegistry } from "./IFlareContractRegistry";
export type { IFtsoV2 } from "./IFtsoV2";
