import {
  Dialog,
  DialogTrigger,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
  DialogClose,
} from './Dialog.js';
import { Button } from './Button.js';

export default {
  title: 'Atomic/Dialog',
  component: Dialog,
};

export const Default = () => (
  <div className="p-8 flex justify-center">
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="primary">Open Enclave Passport</Button>
      </DialogTrigger>

      <DialogContent>
        <DialogHeader>
          <DialogTitle>Attestation Signature Inspection</DialogTitle>
          <DialogDescription>
            Inspect the hardware certificate verification parameters generated by Intel SGX root
            registers.
          </DialogDescription>
        </DialogHeader>

        <div className="bg-[#05060a] p-3 rounded-lg border border-slate-900 font-mono text-[10px] text-slate-400 break-all leading-normal">
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0Yl5c5L1x49Dlh623...[SEALED]
        </div>

        <DialogFooter>
          <DialogClose asChild>
            <Button variant="outline">Close Inspection</Button>
          </DialogClose>
          <Button variant="primary">Download JSON Certificate</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  </div>
);
