import * as React from 'react';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from './Card.js';
import { Badge } from './Badge.js';
import { Cpu, ShieldCheck, Copy, ExternalLink, CheckCircle2, Lock } from 'lucide-react';
import { cn } from '../utils.js';

export interface EnclaveInspectorProps {
  className?: string;
  mrenclave?: string;
  mrsigner?: string;
  strategyHash?: string;
  registryAddress?: string;
  ftsoTimestamp?: number;
}

export function EnclaveInspector({
  className,
  mrenclave = '0x8f3a92b7c4e5110d9842aef610192305a1e2d3c4b5a6f7e8d9c0b1a2f3e4d5c6',
  mrsigner = '0xe4b1109a2f7c001924510aa29e84310da1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d',
  strategyHash = '0x1c89f3a1d94b02e75294a0192c81e9f4a10239b5',
  registryAddress = '0xa513E6E4b8f2a92301c6402A8b213b29c51239b5',
  ftsoTimestamp = Date.now(),
}: EnclaveInspectorProps) {
  const [copiedField, setCopiedField] = React.useState<string | null>(null);

  const handleCopy = (text: string, label: string) => {
    navigator.clipboard.writeText(text);
    setCopiedField(label);
    setTimeout(() => setCopiedField(null), 2000);
  };

  const explorerRegistryUrl = `https://coston2-explorer.flare.network/address/${registryAddress}`;

  return (
    <Card
      className={cn(
        'relative overflow-hidden border-glow bg-slate-950/80 backdrop-blur-2xl',
        className,
      )}
    >
      <CardHeader className="border-b border-white/10 pb-4">
        <div className="flex items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-tr from-cyan-500/20 to-purple-500/20 border border-cyan-500/30 flex items-center justify-center text-cyan-400 shadow-lg shadow-cyan-500/10">
              <Cpu className="w-5 h-5 animate-pulse" />
            </div>
            <div>
              <CardTitle className="text-white text-base md:text-lg flex items-center gap-2 font-display">
                TEE Hardware Attestation Inspector
              </CardTitle>
              <CardDescription className="text-xs text-slate-400">
                Verifiable cryptographic proof generated by AMD SEV-SNP enclave
              </CardDescription>
            </div>
          </div>
          <Badge variant="success" className="px-3 py-1 text-xs">
            Enclave Active & Audited
          </Badge>
        </div>
      </CardHeader>

      <CardContent className="p-6 flex flex-col gap-4 font-sans text-xs">
        {/* Attestation Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {/* MRENCLAVE */}
          <div className="bg-slate-900/80 p-3.5 rounded-xl border border-white/10 flex flex-col gap-1.5">
            <div className="flex items-center justify-between text-slate-400 text-[11px] font-mono uppercase">
              <span className="flex items-center gap-1.5 text-cyan-400 font-semibold">
                <Lock className="w-3 h-3" /> MRENCLAVE (Code Hash)
              </span>
              <button
                onClick={() => handleCopy(mrenclave, 'mrenclave')}
                className="hover:text-white transition-colors cursor-pointer"
                title="Copy Hash"
              >
                {copiedField === 'mrenclave' ? (
                  <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                ) : (
                  <Copy className="w-3.5 h-3.5" />
                )}
              </button>
            </div>
            <div className="font-mono text-[11px] text-slate-200 truncate bg-slate-950/90 p-2 rounded-lg border border-white/5">
              {mrenclave}
            </div>
          </div>

          {/* MRSIGNER */}
          <div className="bg-slate-900/80 p-3.5 rounded-xl border border-white/10 flex flex-col gap-1.5">
            <div className="flex items-center justify-between text-slate-400 text-[11px] font-mono uppercase">
              <span className="flex items-center gap-1.5 text-purple-400 font-semibold">
                <ShieldCheck className="w-3 h-3" /> MRSIGNER (Hardware Authority)
              </span>
              <button
                onClick={() => handleCopy(mrsigner, 'mrsigner')}
                className="hover:text-white transition-colors cursor-pointer"
                title="Copy Hash"
              >
                {copiedField === 'mrsigner' ? (
                  <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                ) : (
                  <Copy className="w-3.5 h-3.5" />
                )}
              </button>
            </div>
            <div className="font-mono text-[11px] text-slate-200 truncate bg-slate-950/90 p-2 rounded-lg border border-white/5">
              {mrsigner}
            </div>
          </div>
        </div>

        {/* Audit Verification Row */}
        <div className="bg-slate-900/60 p-4 rounded-xl border border-cyan-500/20 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center text-emerald-400">
              <ShieldCheck className="w-4.5 h-4.5" />
            </div>
            <div>
              <div className="text-white font-semibold text-xs flex items-center gap-2">
                On-Chain Strategy Registry Verification
              </div>
              <div className="text-[11px] text-slate-400 font-mono flex items-center gap-3 mt-0.5">
                <span>
                  Registry:{' '}
                  <span className="text-cyan-300">
                    {registryAddress.slice(0, 8)}...{registryAddress.slice(-6)}
                  </span>
                </span>
                <span>•</span>
                <span>
                  Hash: <span className="text-purple-300">{strategyHash.slice(0, 8)}...</span>
                </span>
                <span>•</span>
                <span>
                  Oracle Time:{' '}
                  <span className="text-emerald-300">
                    {new Date(ftsoTimestamp).toLocaleTimeString()}
                  </span>
                </span>
              </div>
            </div>
          </div>

          <a
            href={explorerRegistryUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-1.5 bg-cyan-500/10 hover:bg-cyan-500/20 text-cyan-300 border border-cyan-500/30 px-3 py-1.5 rounded-lg text-xs font-semibold transition-all cursor-pointer"
          >
            <span>Verify on Flare Coston2</span>
            <ExternalLink className="w-3.5 h-3.5" />
          </a>
        </div>
      </CardContent>
    </Card>
  );
}
