// SPDX-License-Identifier: MIT
pragma solidity 0.8.20;

/**
 * @title StrategyRegistry
 * @notice Stores generated portfolio rebalancing strategies and recommendations.
 */
contract StrategyRegistry {
  struct Strategy {
    bytes32 id;
    address user;
    uint256 timestamp;
    uint8 healthScore;
    bytes32 reportHash;
  }

  mapping(bytes32 => Strategy) public strategies;
  bytes32[] public strategyIds;

  event StrategyRegistered(
    bytes32 indexed id,
    address indexed user,
    uint256 timestamp,
    uint8 healthScore,
    bytes32 reportHash
  );

  /**
   * @notice Registers a new strategy recommendation generated by the enclave.
   */
  function registerStrategy(bytes32 _id, uint8 _healthScore, bytes32 _reportHash) external {
    require(strategies[_id].id == bytes32(0), 'Strategy already exists');

    Strategy memory newStrategy = Strategy({
      id: _id,
      user: msg.sender,
      timestamp: block.timestamp,
      healthScore: _healthScore,
      reportHash: _reportHash
    });

    strategies[_id] = newStrategy;
    strategyIds.push(_id);

    emit StrategyRegistered(_id, msg.sender, block.timestamp, _healthScore, _reportHash);
  }

  /**
   * @notice Returns the total count of registered strategies.
   */
  function getStrategyCount() external view returns (uint256) {
    return strategyIds.length;
  }
}
