/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IFtsoV2,
  IFtsoV2Interface,
} from "../../../contracts/interfaces/IFtsoV2";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "name",
        type: "string",
      },
    ],
    name: "getFeedByName",
    outputs: [
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
      {
        internalType: "int32",
        name: "decimals",
        type: "int32",
      },
      {
        internalType: "uint64",
        name: "timestamp",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IFtsoV2__factory {
  static readonly abi = _abi;
  static createInterface(): IFtsoV2Interface {
    return new Interface(_abi) as IFtsoV2Interface;
  }
  static connect(address: string, runner?: ContractRunner | null): IFtsoV2 {
    return new Contract(address, _abi, runner) as unknown as IFtsoV2;
  }
}
