/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IFlareContractRegistry__factory } from "./IFlareContractRegistry__factory";
export { IFtsoV2__factory } from "./IFtsoV2__factory";
