/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  AegisAnchor,
  AegisAnchorInterface,
} from "../../contracts/AegisAnchor";

const _abi = [
  {
    inputs: [],
    name: "VERSION",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5060e68061001f6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063ffa1ad7414602d575b600080fd5b6050604051806040016040528060058152602001640312e302e360dc1b81525081565b604051605b91906064565b60405180910390f35b600060208083528351808285015260005b81811015608f578581018301518582016040015282016075565b506000604082860101526040601f19601f830116850101925050509291505056fea26469706673582212200f1a910e21fa6684e15152a0efb876026cfae36fbca801173065490fd6a5567864736f6c63430008140033";

type AegisAnchorConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AegisAnchorConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AegisAnchor__factory extends ContractFactory {
  constructor(...args: AegisAnchorConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      AegisAnchor & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): AegisAnchor__factory {
    return super.connect(runner) as AegisAnchor__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AegisAnchorInterface {
    return new Interface(_abi) as AegisAnchorInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): AegisAnchor {
    return new Contract(address, _abi, runner) as unknown as AegisAnchor;
  }
}
