import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Shield,
  ArrowRight,
  Lock,
  CheckCircle,
  BrainCircuit,
  Activity,
  Cpu,
  BookOpen,
  ChevronDown,
  Network,
  Scale,
  CheckCircle2,
} from 'lucide-react';
import { Button, Badge, cn } from '@aegis/ui';

export default function Landing() {
  const navigate = useNavigate();
  const [activeFaq, setActiveFaq] = useState<number | null>(null);

  // FAQ Accordion List
  const faqItems = [
    {
      q: 'How does Aegis protect my asset allocations from node operators?',
      a: 'Aegis encrypts your balances and targets in the browser before sending them. Computations run entirely within AMD SEV-SNP or Intel SGX hardware-isolated TEE memory enclaves. Host node operators cannot read calculations in memory.',
    },
    {
      q: 'Where do the asset valuations and pricing limits come from?',
      a: 'Pricing feeds are fetched directly from the decentralized Flare Time Series Oracle (FTSOv2). This provides real-time, tamper-proof valuations and collateral checks on-chain without trusting single API endpoints.',
    },
    {
      q: 'What is a TEE Hardware Decision Passport?',
      a: 'It is a cryptographically signed attestation report generated by your secure enclave. The report certifies that the transaction payload was calculated using the exact audited code hash, which is verified by on-chain smart contracts before execution.',
    },
    {
      q: 'Can Aegis automate swaps without my signature?',
      a: 'No. The automated rebalancing contracts only accept payloads accompanied by both a valid hardware enclave attestation signature and your explicit credentials wallet approval.',
    },
  ];

  return (
    <div className="min-h-screen bg-[#05060a] text-slate-100 flex flex-col font-sans relative overflow-x-hidden">
      {/* Background Gradients */}
      <div className="absolute right-[-10%] top-[-10%] w-[600px] h-[600px] bg-indigo-500/5 rounded-full blur-[140px] pointer-events-none" />
      <div className="absolute left-[-10%] bottom-[-10%] w-[600px] h-[600px] bg-orange-500/5 rounded-full blur-[140px] pointer-events-none" />

      {/* Stripe-style background grid lines */}
      <div className="absolute inset-0 bg-[linear-gradient(to_right,rgba(255,255,255,0.015)_1px,transparent_1px),linear-gradient(to_bottom,rgba(255,255,255,0.015)_1px,transparent_1px)] bg-[size:4rem_4rem] [mask-image:radial-gradient(ellipse_60%_50%_at_50%_0%,#000_70%,transparent_100%)] pointer-events-none" />

      {/* Header bar */}
      <header className="border-b border-slate-900/60 bg-[#05060a]/30 backdrop-blur-md relative z-10 select-none">
        <div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-lg bg-indigo-600 flex items-center justify-center shadow-lg shadow-indigo-500/20">
              <Shield className="w-4.5 h-4.5 text-white" />
            </div>
            <div>
              <span className="font-bold text-sm tracking-wider bg-gradient-to-r from-white via-slate-200 to-indigo-400 bg-clip-text text-transparent">
                AEGIS
              </span>
              <span className="text-[8px] block text-slate-500 font-mono tracking-widest leading-none">
                CONFIDENTIAL FINANCIAL INTELLIGENCE
              </span>
            </div>
          </div>
          <Button
            variant="outline"
            size="sm"
            className="border-slate-850 text-slate-300 font-medium"
            onClick={() => navigate('/app/dashboard')}
          >
            Launch App <ArrowRight className="w-3.5 h-3.5" />
          </Button>
        </div>
      </header>

      {/* 1. Hero Section */}
      <section className="relative z-10 max-w-7xl w-full mx-auto px-6 pt-20 pb-16 flex flex-col items-center gap-16 text-center">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="flex flex-col items-center gap-6 max-w-4xl"
        >
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-[10px] font-semibold text-indigo-400 font-mono tracking-wider uppercase">
            <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
            Flare Confidential Compute Sandboxed
          </div>

          <h1 className="text-4xl md:text-6xl font-extrabold tracking-tight leading-tight max-w-4xl font-sans">
            Confidential Financial Intelligence <br />
            <span className="bg-gradient-to-r from-indigo-400 via-slate-200 to-orange-400 bg-clip-text text-transparent">
              Built on Flare Network
            </span>
          </h1>

          <p className="text-slate-400 text-sm md:text-base leading-relaxed max-w-2xl mt-1">
            Analyze portfolios, test risk boundaries, and deploy execution swaps inside secure
            hardware enclaves. Protected calculations backed by on-chain cryptographic attestations.
          </p>

          <div className="flex items-center gap-4 mt-4">
            <Button
              size="lg"
              variant="primary"
              className="h-11 px-6 text-xs"
              onClick={() => navigate('/app/dashboard')}
            >
              Launch Dashboard
            </Button>
            <a href="https://github.com/0xaje/aegis" target="_blank" rel="noopener noreferrer">
              <Button
                size="lg"
                variant="outline"
                className="h-11 px-6 text-xs border-slate-850 text-slate-350"
              >
                <BookOpen className="w-4 h-4" /> Read Integration Guide
              </Button>
            </a>
          </div>
        </motion.div>

        {/* Hero flowchart mockup */}
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="w-full max-w-4xl border border-slate-800/80 bg-[#0c0e14]/50 rounded-2xl p-6 md:p-8 border-glow relative glow-indigo"
        >
          <div className="absolute top-4 left-4 flex items-center gap-2 font-mono text-[9px] text-slate-500">
            <Cpu className="w-3.5 h-3.5" /> SECURE CONTEXT ENGINE
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 items-center mt-6 select-none text-left">
            {/* Step 1 */}
            <div className="bg-[#05060a]/80 border border-slate-900 rounded-xl p-4 flex flex-col gap-3">
              <div className="flex items-center justify-between">
                <span className="text-[9px] font-mono text-slate-500 uppercase font-semibold">
                  User Side
                </span>
                <Lock className="w-3.5 h-3.5 text-indigo-400" />
              </div>
              <span className="text-xs font-semibold text-slate-200">1. Sealed Parameters</span>
              <p className="text-[10px] text-slate-400 leading-normal">
                Balances are encrypted locally in browser memory before leaving the client context.
              </p>
              <div className="font-mono text-[9px] text-slate-600 bg-slate-950 p-2 rounded truncate border border-slate-900/60">
                enc: 0x9bB5e65789d4BBa65a9530de7...
              </div>
            </div>

            {/* Step 2 */}
            <div className="bg-indigo-950/20 border border-indigo-500/25 rounded-xl p-4 flex flex-col gap-3 relative shadow-md shadow-indigo-600/5">
              <div className="flex items-center justify-between">
                <span className="text-[9px] font-mono text-indigo-400 uppercase font-semibold">
                  TEE Enclave
                </span>
                <BrainCircuit className="w-3.5 h-3.5 text-indigo-400 animate-pulse" />
              </div>
              <span className="text-xs font-semibold text-indigo-300">2. Enclave Computation</span>
              <p className="text-[10px] text-slate-350 leading-normal">
                Volatility risk limits are calculated inside isolated memory. No host operator
                visibility.
              </p>
              <div className="flex items-center gap-1.5 text-[9px] text-emerald-400 font-mono font-semibold">
                <CheckCircle2 className="w-3.5 h-3.5" /> INTEL_SGX_SEALED
              </div>
            </div>

            {/* Step 3 */}
            <div className="bg-[#05060a]/80 border border-slate-900 rounded-xl p-4 flex flex-col gap-3">
              <div className="flex items-center justify-between">
                <span className="text-[9px] font-mono text-slate-500 uppercase font-semibold">
                  Coston2 Contract
                </span>
                <Shield className="w-3.5 h-3.5 text-orange-400" />
              </div>
              <span className="text-xs font-semibold text-slate-200">3. Attested Verification</span>
              <p className="text-[10px] text-slate-400 leading-normal">
                Registry verifies enclave image hashes before execution to prevent malicious
                reallocations.
              </p>
              <div className="font-mono text-[9px] text-slate-600 bg-slate-950 p-2 rounded truncate border border-slate-900/60">
                sign: MIIBIjANBgkqhkiG9w0BAQEFAAOC...
              </div>
            </div>
          </div>
        </motion.div>
      </section>

      {/* 2. Features Grid Section */}
      <section className="relative z-10 max-w-7xl w-full mx-auto px-6 py-20 border-t border-slate-900/80 flex flex-col gap-12">
        <div className="max-w-2xl">
          <Badge variant="verified">Features</Badge>
          <h2 className="text-2xl md:text-3xl font-extrabold tracking-tight text-slate-100 mt-3">
            Institutional Risk Framework
          </h2>
          <p className="text-xs text-slate-400 leading-relaxed mt-1.5 max-w-xl">
            Aegis combines confidential compute capabilities with Flare integrations to establish
            secure portfolio optimization tools.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 w-full">
          {/* Feature 1 */}
          <div className="border border-slate-800/80 bg-[#0c0e14]/40 rounded-xl p-6 flex flex-col gap-4">
            <div className="w-9 h-9 rounded-lg bg-orange-500/10 border border-orange-500/20 flex items-center justify-center text-[#FF4A00]">
              <Activity className="w-4.5 h-4.5" />
            </div>
            <h3 className="font-semibold text-sm text-slate-200">Decentralized pricing</h3>
            <p className="text-xs text-slate-400 leading-relaxed">
              Pulls live price indexes directly from Flare Time Series Oracle (FTSOv2) smart feeds
              to run collateral evaluations.
            </p>
          </div>

          {/* Feature 2 */}
          <div className="border border-slate-800/80 bg-[#0c0e14]/40 rounded-xl p-6 flex flex-col gap-4">
            <div className="w-9 h-9 rounded-lg bg-indigo-500/10 border border-indigo-500/20 flex items-center justify-center text-indigo-400">
              <BrainCircuit className="w-4.5 h-4.5" />
            </div>
            <h3 className="font-semibold text-sm text-slate-200">Hardware isolation</h3>
            <p className="text-xs text-slate-400 leading-relaxed">
              Processes sensitive calculations inside sandboxed hardware memory to hide balances
              from host systems.
            </p>
          </div>

          {/* Feature 3 */}
          <div className="border border-slate-800/80 bg-[#0c0e14]/40 rounded-xl p-6 flex flex-col gap-4">
            <div className="w-9 h-9 rounded-lg bg-indigo-500/10 border border-indigo-500/20 flex items-center justify-center text-indigo-400">
              <Cpu className="w-4.5 h-4.5" />
            </div>
            <h3 className="font-semibold text-sm text-slate-200">Execution Passports</h3>
            <p className="text-xs text-slate-400 leading-relaxed">
              Produces verifiable hardware certificates checking image hashes and enclave keys
              before on-chain dispatching.
            </p>
          </div>
        </div>
      </section>

      {/* 3. How It Works Section */}
      <section className="relative z-10 max-w-7xl w-full mx-auto px-6 py-20 border-t border-slate-900/80 flex flex-col gap-12">
        <div className="max-w-2xl">
          <Badge variant="verified">How it works</Badge>
          <h2 className="text-2xl md:text-3xl font-extrabold tracking-tight text-slate-100 mt-3">
            Secure Rebalance Pipeline
          </h2>
          <p className="text-xs text-slate-400 leading-relaxed mt-1.5 max-w-xl">
            Aegis separates transaction definitions from execution layers to isolate user keys and
            asset balances.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
          {[
            {
              step: '01',
              title: 'Parameter Sealing',
              desc: 'Client encrypts portfolio parameters in the browser sandbox.',
            },
            {
              step: '02',
              title: 'Enclave verification',
              desc: 'Secure enclave processes targets against FTSOv2 price feeds.',
            },
            {
              step: '03',
              title: 'Attestation signing',
              desc: 'Hardware signs execution proof containing audited code hash.',
            },
            {
              step: '04',
              title: 'On-chain Execution',
              desc: 'Smart contract registry verifies the attestation signature and executes.',
            },
          ].map((item, idx) => (
            <div
              key={idx}
              className="flex flex-col gap-4 text-left border-l border-slate-800/80 pl-6 relative"
            >
              <span className="font-mono text-2xl font-bold text-indigo-550 text-indigo-500 leading-none">
                {item.step}
              </span>
              <h3 className="font-semibold text-sm text-slate-200">{item.title}</h3>
              <p className="text-xs text-slate-400 leading-relaxed">{item.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* 4. Flare Technology Section */}
      <section className="relative z-10 max-w-7xl w-full mx-auto px-6 py-20 border-t border-slate-900/80 flex flex-col gap-12">
        <div className="max-w-2xl">
          <Badge variant="verified">Flare Integrations</Badge>
          <h2 className="text-2xl md:text-3xl font-extrabold tracking-tight text-slate-100 mt-3">
            Built on Coston2 Infrastructure
          </h2>
          <p className="text-xs text-slate-400 leading-relaxed mt-1.5 max-w-xl">
            Integrating decentralised data queries and hardware verification bounds.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 w-full">
          {/* Flare Confidential Compute */}
          <div className="border border-slate-800/80 bg-[#0c0e14]/40 rounded-xl p-6 md:p-8 flex flex-col gap-4">
            <div className="w-10 h-10 rounded-lg bg-indigo-500/10 flex items-center justify-center text-indigo-400 border border-indigo-500/20">
              <Cpu className="w-5 h-5" />
            </div>
            <h3 className="font-semibold text-base text-slate-200">
              Flare Confidential Compute (FCC)
            </h3>
            <p className="text-xs text-slate-400 leading-relaxed">
              Provides the hardware root of trust. Enclaves run isolated computations, verifying
              that transaction swap conditions correspond to local risk calculations.
            </p>
            <div className="flex items-center gap-1.5 text-[10px] font-mono text-emerald-400 mt-2">
              <CheckCircle className="w-4 h-4" /> Coston2 TEE Registry Active
            </div>
          </div>

          {/* FTSOv2 */}
          <div className="border border-slate-800/80 bg-[#0c0e14]/40 rounded-xl p-6 md:p-8 flex flex-col gap-4">
            <div className="w-10 h-10 rounded-lg bg-orange-500/10 flex items-center justify-center text-[#FF4A00] border border-orange-500/20">
              <Network className="w-5 h-5" />
            </div>
            <h3 className="font-semibold text-base text-slate-200">Decentralised FTSOv2 pricing</h3>
            <p className="text-xs text-slate-400 leading-relaxed">
              Integrates with Flare FTSOv2 registry to fetch asset valuations. Queries feeds
              directly on-chain, securing rebalances against off-chain manipulation or network
              latency.
            </p>
            <div className="flex items-center gap-1.5 text-[10px] font-mono text-emerald-400 mt-2">
              <Scale className="w-4 h-4" /> Oracle Feeds Verified
            </div>
          </div>
        </div>
      </section>

      {/* 5. FAQ Section */}
      <section className="relative z-10 max-w-4xl w-full mx-auto px-6 py-20 border-t border-slate-900/80 flex flex-col gap-12">
        <div className="text-center">
          <Badge variant="verified">FAQ</Badge>
          <h2 className="text-2xl md:text-3xl font-extrabold tracking-tight text-slate-100 mt-3">
            Frequently Asked Questions
          </h2>
        </div>

        <div className="flex flex-col gap-4 w-full">
          {faqItems.map((item, idx) => {
            const isOpen = activeFaq === idx;
            return (
              <div
                key={idx}
                className="border border-slate-850 bg-[#0c0e14]/20 rounded-xl overflow-hidden transition-all duration-200 select-none"
              >
                <button
                  onClick={() => setActiveFaq(isOpen ? null : idx)}
                  className="w-full py-4 px-6 flex items-center justify-between text-left outline-none focus:outline-none"
                >
                  <span className="font-semibold text-xs text-slate-200">{item.q}</span>
                  <ChevronDown
                    className={cn(
                      'w-4 h-4 text-slate-450 text-slate-400 transition-transform duration-200',
                      isOpen && 'rotate-180',
                    )}
                  />
                </button>
                <AnimatePresence initial={false}>
                  {isOpen && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: 'auto', opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.2 }}
                    >
                      <div className="px-6 pb-5 pt-1 text-xs text-slate-400 leading-relaxed font-sans border-t border-slate-900/40">
                        {item.a}
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            );
          })}
        </div>
      </section>

      {/* 6. Footer Section */}
      <footer className="relative z-10 border-t border-slate-900/80 py-8 bg-[#05060a]/40 backdrop-blur-sm mt-auto select-none">
        <div className="max-w-7xl mx-auto px-6 flex flex-col sm:flex-row items-center justify-between gap-6 text-[10px] text-slate-500 font-mono">
          <div className="flex items-center gap-2">
            <Shield className="w-4 h-4 text-indigo-550 text-indigo-500" />
            <span>© 2026 Aegis Confidential Compute. Coston2 Testnet.</span>
          </div>
          <div className="flex gap-4">
            <a
              href="https://github.com/0xaje/aegis"
              className="hover:text-slate-400 transition-colors"
            >
              GitHub Repository
            </a>
            <span>•</span>
            <span className="text-emerald-500 font-semibold">COSTON2 NET ACTIVE</span>
          </div>
        </div>
      </footer>
    </div>
  );
}
